aston_app_ecole:
    resource: "@AstonAppBundle/Resources/config/routing/ecole.yml"
    prefix:   /ecole

aston_app_etudiant:
        resource: "@AstonAppBundle/Resources/config/routing/etudiant.yml"
        prefix:   /etudiant

aston_app_homepage:
    path:     /aston
    defaults: { _controller: AstonAppBundle:Default:index }
