aston_app_etudiants:
    resource: "@ASTONAppBundle/Resources/config/routing/etudiants.yml"
    prefix:   /etudiants

aston_app_homepage:
    path:     /
    defaults: { _controller: ASTONAppBundle:Default:index }
