friend_index:
    path:     /
    defaults: { _controller: "AppliVeroBundle:Friend:index" }
    methods:  GET

friend_show:
    path:     /{id}/show
    defaults: { _controller: "AppliVeroBundle:Friend:show" }
    methods:  GET

friend_new:
    path:     /new
    defaults: { _controller: "AppliVeroBundle:Friend:new" }
    methods:  [GET, POST]

friend_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppliVeroBundle:Friend:edit" }
    methods:  [GET, POST]

friend_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppliVeroBundle:Friend:delete" }
    methods:  DELETE
