aston_blog:
    resource: "@AstonBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

iknsa_app:
    resource: "@IKNSAAppBundle/Resources/config/routing.yml"
    prefix:   /

intro_crud:
    resource: "@introCrudBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

