<<<<<<< Updated upstream
aston_app_etudiant:
    resource: "@AstonAppBundle/Controller/EtudiantController.php"
    type:     annotation

aston_app:
    resource: "@AstonAppBundle/Resources/config/routing.yml"
    prefix:   /

=======
iknsa_blog:
    resource: "@IKNSABlogBundle/Resources/config/routing.yml"
    prefix:   /

iknsa_app:
    resource: "@IKNSAAppBundle/Resources/config/routing.yml"
    prefix:   /

appli_vero:
    resource: "@AppliVeroBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
>>>>>>> Stashed changes
