iknsa_blog_articles:
    resource: "@IKNSABlogBundle/Controller/ArticlesController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

iknsa_blog:
    resource: "@IKNSABlogBundle/Resources/config/routing.yml"
    prefix:   /

aston_app_etudiants:
    resource: "@AstonAppBundle/Controller/EtudiantsController.php"
    type:     annotation

aston_app:
    resource: "@AstonAppBundle/Resources/config/routing.yml"
    prefix:   /