iknsa_blog:
    resource: "@IKNSABlogBundle/Resources/config/routing.yml"
    prefix:   /

aston_app:
    resource: "@astonAppBundle/Resources/config/routing.yml"
    prefix:   /

intro_crud:
    resource: "@introCrudBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

