iknsa_app_homepage:
    path:     /
    defaults: { _controller: IKNSAAppBundle:Default:index }

iknsa_app_etudiant:
    path:     /etudiant
    defaults: { _controller: IKNSAAppBundle:Default:etudiant }