iknsa_app_homepage:
    path:     /iknsa
    defaults: { _controller: IKNSAAppBundle:Default:index }

iknsa_app_homepage:
    path:     /ecole
    defaults: { _controller: IKNSAAppBundle:Default:ecole }
