iknsa_app_homepage:
    path:     /astondf
    defaults: { _controller: IKNSAAppBundle:Default:index }

iknsa_app_ecole:
    path:     /ecole
    defaults: { _controller: IKNSAAppBundle:Default:ecole }
