<?php

namespace ASTON\AppBundle\Repository;

/**
 * etudiantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etudiantsRepository extends \Doctrine\ORM\EntityRepository
{
}
