<?php

namespace intro\CrudBundle\Repository;

/**
 * FirendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirendRepository extends \Doctrine\ORM\EntityRepository
{
}
