<?php

namespace intro\CrudBundle\Repository;

/**
 * friendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class friendRepository extends \Doctrine\ORM\EntityRepository
{
}
