<?php

namespace intro\CrudBundle\Repository;

/**
 * TotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotoRepository extends \Doctrine\ORM\EntityRepository
{
}
