blog_bblog_post:
    resource: "@blogBblogBundle/Resources/config/routing/post.yml"
    prefix:   /post

blog_bblog_homepage:
    path:     /vendor/friendsofsymfony/user-bundle/Resources/views/Registration/register.html.twig
    defaults: { _controller: blogBblogBundle:Default:register }
