eleve_index:
    path:     /
    defaults: { _controller: "AppBundle:Eleve:index" }
    methods:  GET

eleve_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Eleve:show" }
    methods:  GET

eleve_new:
    path:     /new
    defaults: { _controller: "AppBundle:Eleve:new" }
    methods:  [GET, POST]

eleve_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Eleve:edit" }
    methods:  [GET, POST]

eleve_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Eleve:delete" }
    methods:  DELETE
