etudiants_index:
    path:     /
    defaults: { _controller: "AstonAppBundle:Etudiants:index" }
    methods:  GET

etudiants_show:
    path:     /{id}/show
    defaults: { _controller: "AstonAppBundle:Etudiants:show" }
    methods:  GET

etudiants_new:
    path:     /new
    defaults: { _controller: "AstonAppBundle:Etudiants:new" }
    methods:  [GET, POST]

etudiants_edit:
    path:     /{id}/edit
    defaults: { _controller: "AstonAppBundle:Etudiants:edit" }
    methods:  [GET, POST]

etudiants_delete:
    path:     /{id}/delete
    defaults: { _controller: "AstonAppBundle:Etudiants:delete" }
    methods:  DELETE
