article_article:
    resource: "@ArticleBundle/Resources/config/routing/article.yml"
    prefix:   /article

article_homepage:
    path:     /apparticle
    defaults: { _controller: ArticleBundle:Default:index }
